Repository OZ-Coding-School/oz_03_collabo-002-FE, pull requests merged in 2024-08, with the labels that each got.

#1 [Fix] tailwindcss 적용되지 않는 오류 해결
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/home/Home.tsx
  tailwind.config.js
  tsconfig.app.json
Labels: bug

#4 [Chore] ci문서에 Build 코드 추가
  .github/workflows/ci.yml
  .github/workflows/node.js.yml
Labels: documentation

#2 [Feat] msw 목업 서버 설정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/axios.ts
  src/components/home/Home.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/data/classList.json
  src/mocks/data/user.ts
  src/mocks/handlers.ts
  src/store/useClassStore.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#10 [Design] 회원가입 페이지 ui 작업
  src/App.tsx
  src/icon/facebook.svg
  src/icon/google.svg
  src/icon/kakao.svg
  src/icon/naver.svg
  src/icon/signup_profile.svg
  src/pages/ChargePage.tsx
  src/pages/MyPage.tsx
  src/pages/findId.tsx
  src/pages/findPassword.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: enhancement

#11 [Feat] 클래스 카드 및 카드 리스트 컴포넌트 생성
  index.html
  package-lock.json
  src/App.css
  src/components/common/CardList.tsx
  src/components/common/ClassCard.tsx
  src/components/common/Header.tsx
  src/index.css
  src/mocks/data/classList.json
  src/pages/ChargePage.tsx
  src/pages/MyPage.tsx
  src/pages/findId.tsx
  src/pages/findPassword.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
  src/store/useClassStore.ts
  tailwind.config.js
Labels: enhancement

#13 [Chore] package.json에 type-check 추가
  .github/workflows/ci.yml
  package.json
  src/App.tsx
Labels: invalid

#12 [Design] modal ui 작업
  src/App.tsx
  src/components/common/Modal.tsx
  src/icon/arrow-left.svg
  src/pages/SignUp.tsx
  src/store/useModal.ts
  src/type/types.ts
Labels: enhancement

#15 [Feat]button
  src/App.tsx
  src/components/common/Button.tsx
Labels: Feat

#16 [Chore] issue templates 재등록
  .github/ISSUE_TEMPLATE/--feat--기능-개발-요청.md
  .github/ISSUE_TEMPLATE/-bug--오류-수정-요청.md
  .github/ISSUE_TEMPLATE/-etc---다양한-주제.md
Labels: Chore

#17 [Chore] pull_request_template 수정
  .github/pull_request_template.md
Labels: Chore

#27 [Style] Review Page ui 작업
  public/images/서울.jpg
  src/App.tsx
  src/assets/icon/arrow-left.svg
  src/assets/icon/empty-heart.svg
  src/assets/icon/empty-star.svg
  src/assets/icon/facebook.svg
  src/assets/icon/full-heart.svg
  src/assets/icon/full-star.svg
  src/assets/icon/google.svg
  src/assets/icon/kakao.svg
  src/assets/icon/naver.svg
  src/assets/icon/signup_profile.svg
  src/components/review/Review.tsx
  src/components/review/ReviewHeader.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/components/review/ReviewModal.tsx
  src/components/review/ReviewTotal.tsx
  src/mocks/data/reviews.json
  src/mocks/handlers.ts
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/type/types.ts
Labels: Style

#28 [Feat] 결제 페이지 UI 생성
  src/assets/icon/icon-remove.svg
  src/assets/icon/index.tsx
  src/components/order/Order.tsx
  src/index.css
  src/pages/ChargePage.tsx
  src/type/order.ts
  tailwind.config.js
Labels: Feat

#31 [Feat] 좋아요 페이지 UI 생성
  src/App.tsx
  src/pages/LikesPage.tsx
  src/store/useClickedCardStore.ts
  src/store/useLikeStore.ts
Labels: 6h

#33 [Feat] 나의 주문목록 페이지 UI 생성
  package-lock.json
  package.json
  src/assets/icon/icon-check.svg
  src/assets/icon/index.tsx
  src/components/account/Account.tsx
  src/components/account/AccountDashboard.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyTodayWorkshops.tsx
  src/index.css
  src/mocks/data/payment_history.json
  src/mocks/data/user.json
  src/mocks/handlers.ts
  src/pages/Login.tsx
  src/store/useAccount.ts
  src/type/account.ts
Labels: Feat, Chore

#40 [Refactor]헤더 Link 설정
  src/App.tsx
  src/components/classDetail/ClassDetailPhotoReview.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/Header.tsx
Labels: refactor

#41 [Feat] 회원정보 수정 페이지 생성
  public/images/user-empty.png
  src/assets/icon/icon-user-avatar.svg
  src/components/account/Account.tsx
  src/components/account/AccountDashboard.tsx
  src/components/account/AccountEditProfile.tsx
  src/components/account/AccountHeader.tsx
  src/components/account/AccountUserInfo.tsx
  src/components/account/MyOrderList.tsx
  src/components/common/Button.tsx
  src/config/IconData.tsx
  src/mocks/data/user.json
  src/store/useAccountStore.ts
  src/type/account.ts
  tailwind.config.js
Labels: Feat

#42 [Feat] 클래스 카테고리별 보기 생성
  src/App.tsx
  src/components/classByCategory/ClassByCategory.tsx
  src/components/classByCategory/classByCategory.tsx
Labels: Feat

#52 Fix: build 에러 긴급 패치
  src/components/account/AccountDashboard 2.tsx
  src/main.tsx
  src/store/useAccount.ts
Labels: Fix

#53 [Feat] 회원가입 유효성 검사 및 api 연결
  src/App.tsx
  src/assets/icon/success-check.svg
  src/components/Login/FaceBook.tsx
  src/components/Login/Google.tsx
  src/components/Login/Kakao.tsx
  src/components/Login/Naver.tsx
  src/main.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/type/signup.ts
Labels: Feat

#56 [Feat] 회원정보 수정 및 계정 삭제 api 생성 #49 #50
  src/components/account/AccountEditProfile.tsx
  src/components/account/MyOrderList 2.tsx
  src/components/account/MyOrderList.tsx
  src/store/useAccount.ts
  src/store/useAccountStore.ts
  src/type/account.type.ts
Labels: Feat

#59 Conf: deploy 코드작성 및 설정 #58
  .github/workflows/deploy.yml
  deploy_script.js
  package-lock.json
  package.json
Labels: Conf

#60 [Feat] 일반 로그인 및 소셜 로그인(Line 추가) 및 회원가입 로직추가
  package-lock.json
  package.json
  src/assets/icon/line.svg
  src/components/Login/Kakao.tsx
  src/components/Login/Line.tsx
  src/components/Login/Naver.tsx
  src/components/common/ModalProfile.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/store/useUser.ts
  src/type/loginuser.ts
  src/type/signup.ts
  src/type/user.ts
  vite.config.ts
Labels: Feat

#55 [Feat] 리뷰보기 api 기능 추가
  src/App.tsx
  src/api/axios.ts
  src/assets/icon/icon-remove.svg
  src/assets/icon/icon-review-star-empty.svg
  src/components/common/RatingAverage.tsx
  src/components/review/Review.tsx
  src/components/review/ReviewHeader.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/components/review/ReviewModal.tsx
  src/config/IconData.tsx
  src/index.css
  src/mocks/data/payment_history.json
  src/mocks/data/reviews.json
  src/mocks/handlers.ts
  src/store/useClassStore.ts
  src/store/useReviewStore.ts
  src/type/review.type.ts
  src/type/types.ts
Labels: Feat

#68 [Conf] 배포파일 수정
  .github/workflows/deploy.yml
  deploy_script.js
  package-lock.json
  package.json
Labels: Conf

#69 Release 0.1
  .github/workflows/deploy.yml
  deploy_script.js
  package-lock.json
  package.json
Labels: Delpoy

#71 [Feat] 카테고리 페이지 api 등록 및 라우트 설정 #57
  src/App.tsx
  src/components/classByCategory/Category.tsx
  src/components/classByCategory/CategoryHeader.tsx
  src/components/classByCategory/ClassByCategory.tsx
  src/components/common/Header.tsx
  src/components/home/Home.tsx
  src/components/home/HomeCategoryList.tsx
  src/components/home/HomeSlideBanner.tsx
  src/mocks/data/classList.json
  src/type/class.type.ts
Labels: Feat

#72 [Feat] 문의 api - CRUD #43
  src/api/axios.ts
  src/assets/icon/icon-edit.svg
  src/assets/icon/icon-login.svg
  src/components/account/Account.tsx
  src/components/account/AccountEditProfile.tsx
  src/components/account/AccountUserInfo.tsx
  src/components/account/MyOrderList 2.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestion.tsx
  src/components/account/MyQuestions.tsx
  src/components/classDetail/ClassDetailQna.tsx
  src/components/classDetail/ClassDetailQnaAll.tsx
  src/components/common/Header.tsx
  src/components/question/CreateQuestionModal.tsx
  src/components/question/EditQuestionModal.tsx
  src/components/question/MyQuestion.tsx
  src/components/question/MyQuestionList.tsx
  src/components/question/QuestionItem.tsx
  src/components/question/QuestionModal.tsx
  src/config/IconData.tsx
  src/main.tsx
  src/store/useAccountStore.ts
  src/store/useQnaStore.ts
  src/store/useQuestionStore.ts
  src/store/useUser.ts
  src/type/account.type.ts
  src/type/question.ts
  src/type/question.type.ts
  src/type/user.ts
Labels: Feat

#73 Conf: 배포코드 재수정 - 전체삭제후 업로드
  deploy_script.js
Labels: Conf

#74 [Deploy] 2차 수정 배포
  deploy_script.js
  src/api/axios.ts
  src/assets/icon/icon-edit.svg
  src/assets/icon/icon-login.svg
  src/components/account/Account.tsx
  src/components/account/AccountEditProfile.tsx
  src/components/account/AccountUserInfo.tsx
  src/components/account/MyOrderList 2.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestion.tsx
  src/components/account/MyQuestions.tsx
  src/components/classDetail/ClassDetailQna.tsx
  src/components/classDetail/ClassDetailQnaAll.tsx
  src/components/common/Header.tsx
  src/components/question/CreateQuestionModal.tsx
  src/components/question/EditQuestionModal.tsx
  src/components/question/MyQuestion.tsx
  src/components/question/MyQuestionList.tsx
  src/components/question/QuestionItem.tsx
  src/components/question/QuestionModal.tsx
  src/config/IconData.tsx
  src/main.tsx
  src/store/useAccountStore.ts
  src/store/useQnaStore.ts
  src/store/useQuestionStore.ts
  src/store/useUser.ts
  src/type/account.type.ts
  src/type/question.ts
  src/type/question.type.ts
  src/type/user.ts
Labels: Delpoy

#76 [Feat] 로그인, 회원가입 및 리뷰 모달 로직 수정
  src/App.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/review/Review.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewPhotoModal.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/type/signup.ts
Labels: 6h

#77 [Deploy] 3차 배포
  .github/workflows/deploy.yml
  package-lock 2.json
  package-lock.json
  public/images/img-sample 2.jpg
  public/images/img-sample2 2.jpg
  public/images/img-sample3 2.jpg
  public/images/img-sample4 2.jpg
  public/images/서울 2.jpg
  public/mockServiceWorker 2.js
  src/App.tsx
  src/components/classDetail/ClassDetail.tsx
  src/components/classDetail/ClassDetailClassContent.tsx
  src/components/classDetail/ClassDetailContent.tsx
  src/components/classDetail/ClassDetailImageSlide.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailReservation.tsx
  src/components/common/ClassCard.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/home/KpickClasses.tsx
  src/components/home/NewClasses.tsx
  src/components/home/PopularClasses.tsx
  src/components/review/Review.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewPhotoModal.tsx
  src/mocks/handlers.ts
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/store/useClassStore.ts
  src/type/class.ts
  src/type/class.type.ts
  src/type/signup.ts
  vite.config.ts.timestamp-1724292411180-d921ada7f510d.mjs
Labels: Delpoy

#81 [Feat] 찜 뷰 UI 생성 및 api 코드 작성
  src/App.tsx
  src/components/account/Account.tsx
  src/components/account/MyLike.tsx
  src/components/common/ClassCard.tsx
  src/store/useLikeStore.ts
Labels: Feat

#82 [Deploy] 이미지 url 수정 및 찜 기능 구현
  npm-cache/_update-notifier-last-checked
  src/App.tsx
  src/components/account/Account.tsx
  src/components/account/MyLike.tsx
  src/components/common/ClassCard.tsx
  src/store/useLikeStore.ts
Labels: Delpoy

#84 [Deploy] 찜 클릭 에러 수정 배포
  src/components/common/ClassCard.tsx
Labels: Fix

#85 Fix: 마이페이지 내 데이터 없는경우 예외처리
  src/components/account/Account.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestion.tsx
  src/components/account/MyQuestionList.tsx
  src/components/account/MyReview.tsx
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Fix

#86 [Deploy] 마이페이지 예외처리 반영
  src/components/account/Account.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestion.tsx
  src/components/account/MyQuestionList.tsx
  src/components/account/MyReview.tsx
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Delpoy

#88 [Feat] 리뷰 작성 모달 창 api 연결 및 유효성 검사 & redirection api 로직 수정
  src/components/common/ModalReviewWrite.tsx
  src/pages/Redirection.tsx
Labels: Feat

#89 [Deploy] 5차
  src/components/common/ModalReviewWrite.tsx
  src/pages/Redirection.tsx
Labels: Delpoy

#92 [Deploy] 리뷰 작성 모달 api 수정 반영
  src/components/common/Modal.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewPhotoModal.tsx
  src/pages/SignUp.tsx
  src/type/review.type.ts
Labels: Delpoy

#93 [Fix] deploy 코드파일 복구
  .github/workflows/deploy.yml
  deploy_script.js
Labels: Fix

#94 [Deploy]Fix: deploy 코드 복구 반영
  .github/workflows/deploy.yml
  deploy_script.js
Labels: Delpoy
