Repository OZ-Coding-School/oz_03_collabo-002-FE, pull requests merged in 2024-09, with the labels that each got.

#96 [Feat] Line 소셜 로그인 state 코드 전달하기 위해 조건문 로직 수정
  src/pages/Redirection.tsx
Labels: Feat

#97 [Deploy] Line 소셜 로그인 코드 수정 반영
  src/pages/Redirection.tsx
Labels: Delpoy

#100 [Feat] 마이페이지 내 빈데이터 출력문구 수정
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestionList.tsx
  src/components/account/MyReview.tsx
Labels: Feat

#98 [feat] 클래스 상세 페이지 api 수정 및 슬라이드 이미지 코드 변경
  src/App.tsx
  src/components/account/MyOrderList.tsx
  src/components/classDetail/ClassDetailInfoSlide.tsx
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/components/common/ClassCard.tsx
  src/components/common/RatingAverage.tsx
  src/pages/ClassDetail.tsx
  src/store/useClassStore.ts
  src/type/class.type.ts
Labels: Feat

#102 [Feat] token을 저장
  package-lock.json
  package.json
  src/App.tsx
  src/components/Login/LineEmail.tsx
  src/components/common/ModalReviewWrite.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/type/user.ts
Labels: 2h

#103 [Deploy] 변경내용 반영하여 재배포(상세)
  package-lock.json
  package.json
  src/App.tsx
  src/components/Login/LineEmail.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestionList.tsx
  src/components/account/MyReview.tsx
  src/components/classDetail/ClassCalendar.tsx
  src/components/classDetail/ClassDetailCalendarSlide.tsx
  src/components/classDetail/ClassDetailInfoSlide.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/components/common/ClassCard.tsx
  src/components/common/Header.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/home/HomeCategoryList.tsx
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/store/useBookingStore.ts
  src/store/useClassStore.ts
  src/type/class.type.ts
  src/type/user.ts
Labels: Delpoy

#104 [Fix] 클래스 썸네일 이미지 크기 조정
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/common/ClassCard.tsx
  src/pages/ClassDetail.tsx
Labels: Fix

#105 [Deploy] Fix 이미지 사이즈 오류 수정 반영
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/common/ClassCard.tsx
  src/pages/ClassDetail.tsx
Labels: Delpoy

#108 [Deploy] 페이지에서 리뷰 하나만 보이게 로직 수정
  .github/workflows/ci.yml
  deploy_script.js
  src/components/classDetail/ClassDetailReview.tsx
Labels: Delpoy

#109 [Deploy] 배포코드 재수정 후 재배포
  deploy_script.js
Labels: Delpoy

#110 [Deploy] 배포코드 재수정 - 파일 삭제 코드 제거
  deploy_script.js
Labels: Delpoy

#111 [Deploy] 배포코드 재수정 - 컨텐츠 타입 지정코드 추가
  deploy_script.js
  package-lock.json
  package.json
Labels: Delpoy

#112 [Deploy] 배포코드 재수정 - 브라우저로 열리도록 수정
  deploy_script.js
Labels: Delpoy

#115 [Feat] 전체 리뷰 보기 api 연결 및 리뷰 버튼(임시) 클릭 추가
  deploy_script.js
  src/App.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/ClassDetail.tsx
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Feat

#116 [Deploy] 시연을 위한 배포
  deploy_script.js
  src/App.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/ClassDetail.tsx
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Delpoy

#117 [Feat] 마이페이지 전체 점검
  src/App.tsx
  src/api/axios.ts
  src/assets/icon/icon-edit.svg
  src/assets/icon/icon-remove.svg
  src/components/account/Account.tsx
  src/components/account/AccountDashboard.tsx
  src/components/account/AccountEditPhoto.tsx
  src/components/account/AccountEditProfile.tsx
  src/components/account/AccountHeader.tsx
  src/components/account/AccountUserInfo.tsx
  src/components/account/MyLike.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestionList.tsx
  src/components/account/MyReview.tsx
  src/components/account/MyReviews.tsx
  src/components/classByCategory/Category.tsx
  src/components/classDetail/ClassDetailQna.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/question/ClassDetailQnaAll.tsx
  src/components/question/CreateQuestionModal.tsx
  src/components/question/EditQuestionModal.tsx
  src/components/question/QuestionItem.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewPhotoModal.tsx
  src/mocks/data/qna.json
  src/pages/ClassDetail.tsx
  src/store/useAccountStore.ts
  src/store/useClassStore.ts
  src/store/useQuestionStore.ts
  src/store/useReviewStore.ts
  src/store/useUser.ts
  src/type/account.type.ts
  src/type/class.type.ts
  src/type/question.type.ts
  src/type/review.type.ts
  src/type/user.ts
Labels: Fix, Feat

#118 [Deploy] 마이페이지 수정 반영 배포
  src/App.tsx
  src/api/axios.ts
  src/assets/icon/icon-edit.svg
  src/assets/icon/icon-remove.svg
  src/components/account/Account.tsx
  src/components/account/AccountDashboard.tsx
  src/components/account/AccountEditPhoto.tsx
  src/components/account/AccountEditProfile.tsx
  src/components/account/AccountHeader.tsx
  src/components/account/AccountUserInfo.tsx
  src/components/account/MyLike.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyQuestionList.tsx
  src/components/account/MyReview.tsx
  src/components/account/MyReviews.tsx
  src/components/classByCategory/Category.tsx
  src/components/classDetail/ClassDetailQna.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/question/ClassDetailQnaAll.tsx
  src/components/question/CreateQuestionModal.tsx
  src/components/question/EditQuestionModal.tsx
  src/components/question/QuestionItem.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewPhotoModal.tsx
  src/mocks/data/qna.json
  src/pages/ClassDetail.tsx
  src/store/useAccountStore.ts
  src/store/useClassStore.ts
  src/store/useQuestionStore.ts
  src/store/useReviewStore.ts
  src/store/useUser.ts
  src/type/account.type.ts
  src/type/class.type.ts
  src/type/question.type.ts
  src/type/review.type.ts
  src/type/user.ts
Labels: Delpoy

#119 [hotfix]회원가입 이미지 미첨부 오류
  src/components/account/MyQuestionList.tsx
  src/pages/SignUp.tsx
  src/type/user.ts
Labels: Fix

#120 [hotfix] 회원가입 api 요청주소 오류 수정
  src/pages/SignUp.tsx
Labels: Fix

#122 [Feat] 리뷰 작성 api 로직 수정
  src/App.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/store/useUser.ts
  src/type/signup.ts
Labels: Feat

#123 [Feat] 클래스 카드 태그 수정 및 컨텐츠 위치 수정
  src/components/common/ClassCard.tsx
Labels: Style, Chore

#126 [Fix]빌드 에러 수정
  src/App.tsx
  src/components/classDetail/ClassCalendar.tsx
  src/components/classDetail/ClassDetailInfoSlide.tsx
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/common/ClassCard.tsx
  src/components/question/CreateQuestionModal.tsx
  src/pages/ClassDetail.tsx
  src/store/useClassStore.ts
  src/type/class.type.ts
Labels: Fix

#127 [Fix] api 요청 에러 수정
  src/App.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/pages/ClassDetail.tsx
  src/store/useClassStore.ts
Labels: Fix

#129 [Feat] 클래스 카드 클릭 버블링 현상 해소
  src/components/common/ClassCard.tsx
  src/components/common/ToggleButtonHeart.tsx
Labels: Feat

#131 [Feat] 결제 api 생성ㅇㅇ
  src/App.tsx
  src/components/account/MyInfo.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyTodayWorkshops.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderComplete.tsx
  src/components/order/OrderDepositPage.tsx
  src/components/order/OrderDepositorBtn.tsx
  src/components/order/OrderDetail.tsx
  src/components/order/OrderHeader.tsx
  src/components/order/OrderMain.tsx
  src/components/order/OrderPayPalBtn.tsx
  src/pages/ChargePage.tsx
  src/pages/ClassDetail.tsx
  src/store/useBookingStore.ts
  src/store/useOrderStore.ts
  src/type/order.type.ts
Labels: Feat

#132 [Deploy] 결제페이지 반영
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/icon-check.svg
  src/components/account/MyInfo.tsx
  src/components/account/MyOrderList.tsx
  src/components/account/MyTodayWorkshops.tsx
  src/components/classDetail/ClassCalendar.tsx
  src/components/classDetail/ClassDetail.css
  src/components/classDetail/ClassDetailCalendarSlide.tsx
  src/components/classDetail/ClassDetailInfoSlide.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailPhotoReview.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/components/common/ClassCard.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/Policy.tsx
  src/components/common/Terms.tsx
  src/components/common/ToggleButtonHeart.tsx
  src/components/home/HomeCategoryList.tsx
  src/components/home/PopularClasses.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderComplete.tsx
  src/components/order/OrderDepositPage.tsx
  src/components/order/OrderDepositorBtn.tsx
  src/components/order/OrderDetail.tsx
  src/components/order/OrderHeader.tsx
  src/components/order/OrderMain.tsx
  src/components/order/OrderPayPalBtn.tsx
  src/components/question/CreateQuestionModal.tsx
  src/components/question/EditQuestionModal.tsx
  src/components/question/QuestionModal.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/ChargePage.tsx
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/store/useBookingStore.ts
  src/store/useClassStore.ts
  src/store/useModal.ts
  src/store/useOrderStore.ts
  src/store/useUser.ts
  src/type/class.type.ts
  src/type/order.type.ts
  src/type/signup.ts
  src/type/types.ts
  src/utils/timeUtils.ts
Labels: Delpoy

#133 [Chore] 클래스카드 주소영역 카테고리로 대치
  src/components/common/ClassCard.tsx
Labels: Chore

#134 [Feat] 카테고리 복수선택 변경에 따른 로직 변경
  src/components/classByCategory/Category.tsx
Labels: Feat

#125 [Feat] 로그인 및 회원가입 axios 수정 및 리뷰 업데이트 로직 추가
  src/api/axios.ts
  src/components/account/AccountUserInfo.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/store/useAccountStore.ts
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Feat

#135 [Deploy] axios api 반영
  src/api/axios.ts
  src/components/account/AccountUserInfo.tsx
  src/components/classByCategory/Category.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/ClassCard.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/store/useAccountStore.ts
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Delpoy

#136 [Feat] 결제 api 1차 테스트
  src/components/account/MyOrderList.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderComplete.tsx
  src/components/order/OrderDetail.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/main.tsx
  src/pages/ClassDetail.tsx
  src/store/useBookingStore.ts
  src/store/useOrderStore.ts
  src/type/order.type.ts
Labels: Feat

#138 [Feat] 리뷰 업데이트 로직 수정 및 총 리뷰 수 api 연결
  src/components/classDetail/ClassDetailReview.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/review/Review.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/pages/ClassDetail.tsx
  src/store/useReviewStore.ts
  src/type/review.type.ts
Labels: Feat

#139 [Feat] 리뷰 생성 및 업데이트 로직 수정 완료
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/review/Review.tsx
  src/components/review/ReviewItem.tsx
  src/pages/Login.tsx
  src/store/useClassStore.ts
  src/type/class.type.ts
Labels: Feat

#142 [Fix] 문의 수정 후 리렌더링 에러 해결
  src/api/axios.ts
  src/components/account/MyQuestionList.tsx
  src/components/question/CreateQuestionModal.tsx
  src/components/question/EditQuestionModal.tsx
  src/store/useQuestionStore.ts
  src/type/question.type.ts
Labels: Fix

#143 [Fix] 문의목록에 클래스타이틀 추가 & 나의 리뷰목록 필터코드 추가
  src/components/account/MyQuestionList.tsx
  src/store/useClassStore.ts
  src/store/useReviewStore.ts
  src/type/class.type.ts
  src/type/review.type.ts
Labels: Fix

#144 [Fix] 찜기능 기능 수정 & 결제 api 코드 수정
  src/components/account/MyLike.tsx
  src/components/common/EmptyData.tsx
  src/components/common/ToggleButtonHeart.tsx
  src/components/order/OrderButton.tsx
  src/store/useClassStore.ts
  src/store/useLikeStore.ts
  src/type/like.type.ts
Labels: Fix

#145 [Feat] 리뷰 업데이트 및 axios, token 로직 수정
  src/api/axios.ts
  src/components/common/ModalReviewWrite.tsx
  src/components/common/RatingAverage.tsx
  src/components/review/Review.tsx
  src/components/review/ReviewItem.tsx
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/pages/Redirection.tsx
  src/pages/SignUp.tsx
  src/store/useAccountStore.ts
Labels: Feat

#147 [Feat] navigate 경로 / 추가
  src/pages/ClassDetail.tsx
Labels: Feat

#148 [Deploy] 엔드포인트 오류 일부 수정
  src/pages/ClassDetail.tsx
Labels: Delpoy

#149 feat: 로그인 axios 수정
  src/pages/Login.tsx
Labels: Feat

#150 [Deploy] api import 수정
  src/pages/Login.tsx
Labels: Delpoy

#151 feat: restapi 추가
  src/components/Login/Kakao.ts
Labels: Feat

#152 [Chore] 메인영역 카테고리 UI 변경
  public/Home/CategoryList/category-activities.png
  public/Home/CategoryList/category-all.png
  public/Home/CategoryList/category-art-culture.png
  public/Home/CategoryList/category-beauty-fashion.png
  public/Home/CategoryList/category-cooking.png
  public/Home/CategoryList/category-diy.png
  src/components/home/HomeCategoryList.tsx
  src/store/useLikeStore.ts
Labels: Fix, Chore

#153 [Fix] 디테일 페이지 정보출력 컴포넌트 수정
  src/App.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/pages/ClassDetail.tsx
Labels: Fix

#154 [Fix] 주문정보 관련 데이터 형식 전체 수정
  src/components/classDetail/ClassCalendar.tsx
  src/components/classDetail/ClassDetailCalendarSlide.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailSelectOption.tsx
  src/components/classDetail/ClassDetailSlide.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/components/classDetail/GoodsDetailTopInfo.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderDetail.tsx
  src/components/order/OrderMain.tsx
  src/pages/ChargePage.tsx
  src/pages/ClassDetail.tsx
  src/store/useBookingStore.ts
Labels: Fix, Feat

#156 [Deploy] 임시 도메인 연결 및 기타 에러 수정
  package-lock 2.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/api/axios.ts
  src/assets/icon/index.tsx
  src/components/classDetail/ClassDetailContent.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailReview.tsx
  src/components/classDetail/ClassDetailSelectOption.tsx
  src/components/classDetail/ClassDetailTopInfo.tsx
  src/components/common/RatingAverage.tsx
  src/components/common/ToggleButtonHeart.tsx
  src/components/home/HomeCategoryList.tsx
  src/components/home/PopularClasses.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderDepositPage.tsx
  src/config/IconData.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/data/classList.json
  src/mocks/data/payment_history.json
  src/mocks/data/qna.json
  src/mocks/data/reviews.json
  src/mocks/data/user.json
  src/mocks/data/user.ts
  src/mocks/handlers.ts
  src/pages/ChargePage.tsx
  src/pages/ClassDetail.tsx
  src/pages/Login.tsx
  src/store/useClassStore.ts
  src/type/class.type.ts
  vite.config.ts
Labels: Delpoy

#158 [Fix] 콜백api 요청 key 변경
  src/components/Login/Kakao.ts
  src/pages/Redirection.tsx
Labels: Fix

#163 [Deploy] 커밋 복구 및 환경변수 test
  .github/workflows/deploy.yml
  package-lock.json
  src/App.tsx
  src/components/Login/Kakao.ts
  src/components/classDetail/ClassDetailPolicy.tsx
  src/components/common/Footer.tsx
  src/components/common/Modal.tsx
  src/components/order/OrderButton.tsx
  src/pages/Redirection.tsx
  vite.config.ts
Labels: Delpoy

#164 [Deploy] 환경변수 test
  .github/workflows/deploy.yml
  src/components/Login/Kakao.ts
Labels: Delpoy

#165 [Deploy] 환경변수 test 코드 제거
  .github/workflows/deploy.yml
  src/App.tsx
  src/components/Login/Kakao.ts
Labels: Delpoy

#166 [Feat] 페이팔 코드 개선
  src/components/account/Account.tsx
  src/components/account/MyOrderList.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailSelectOption.tsx
  src/components/common/ClassCard.tsx
  src/components/common/Header.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/ToggleButtonHeart.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderDepositPage.tsx
  src/components/order/OrderDetail.tsx
  src/pages/ChargePage.tsx
  src/pages/SignUp.tsx
  src/store/useBookingStore.ts
  src/store/useLikeStore.ts
  src/store/useOrderStore.ts
  src/type/order.type.ts
Labels: Fix, Feat, Chore

#167 [Deploy] 결제 및 찜기능, 로그인라우터 반영
  src/components/account/Account.tsx
  src/components/account/MyOrderList.tsx
  src/components/classDetail/ClassDetailOption.tsx
  src/components/classDetail/ClassDetailSelectOption.tsx
  src/components/common/ClassCard.tsx
  src/components/common/Header.tsx
  src/components/common/ModalReviewWrite.tsx
  src/components/common/ToggleButtonHeart.tsx
  src/components/order/OrderButton.tsx
  src/components/order/OrderDepositPage.tsx
  src/components/order/OrderDetail.tsx
  src/pages/ChargePage.tsx
  src/pages/SignUp.tsx
  src/store/useBookingStore.ts
  src/store/useLikeStore.ts
  src/store/useOrderStore.ts
  src/type/order.type.ts
Labels: Delpoy
